{{- if and .Values.secret.data (not .Values.vault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-nodejs.fullname" . }}
  labels:
    {{- include "sample-nodejs.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
